# Generated by Django 4.2.9 on 2026-02-12 18:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_stock_close_price_stock_dividend_yield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='percentage_change',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_change',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
