# Generated by Django 4.2.9 on 2026-03-01 18:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0003_stock_percentage_change_stock_price_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='market_cap',
            new_name='quote_volume_24h',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='dividend_yield',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='pe_ratio',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
        migrations.AddField(
            model_name='stock',
            name='ask_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='base_asset',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='high_24h',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='low_24h',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='quote_asset',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Last Price'),
        ),
    ]
