# Generated by Django 4.2.9 on 2026-03-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0004_rename_market_cap_stock_quote_volume_24h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
