# Generated by Django 4.2.9 on 2026-03-13 21:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0005_stock_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ask_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bid_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='close_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12, verbose_name='Last Price'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high_24h',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low_24h',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='percentage_change',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_change',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quote_volume_24h',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=20),
        ),
    ]
