# Generated by Django 5.2 on 2025-11-08 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('REQUESTED', 'REQUESTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='REQUESTED', max_length=15)),
                ('transaction_type', models.CharField(choices=[('WITHDRAW', 'WITHDRAW'), ('DEPOSIT', 'DEPOSIT')], default='WITHDRAW', max_length=15)),
                ('amount', models.PositiveIntegerField(default=0.0)),
                ('wallet', models.FloatField(default=0.0)),
                ('remark', models.CharField(default='Secured Payment', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
