# Generated by Django 5.2 on 2025-11-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_settings_remove_payment_plan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
