# Generated by Django 5.2 on 2025-11-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_delete_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='manual_payments/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
