# Generated by Django 4.2.9 on 2025-11-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_transaction_wallet_transaction_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='promo_code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='promo_code_reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
