# Generated by Django 4.2.9 on 2025-11-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_promo_code_transaction_promo_code_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
