# Generated by Django 5.2 on 2025-11-01 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0)),
                ('last_traded_quantity', models.IntegerField(default=0)),
                ('buy_price', models.FloatField(default=0.0)),
                ('sell_price', models.FloatField(default=0.0)),
                ('realised_pnl', models.FloatField(default=0.0)),
                ('last_traded_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('initiated', 'initiated'), ('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('failed', 'failed')], default='pending', max_length=10)),
                ('amount', models.FloatField(default=0.0)),
                ('order_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='', max_length=5)),
                ('charges', models.FloatField(default=0.0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.stock')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.position')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
