# Generated by Django 5.2 on 2025-11-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_open',
            field=models.BooleanField(default=False),
        ),
    ]
