# Generated by Django 5.2 on 2025-11-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_position_position_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position_open',
            new_name='is_closed',
        ),
    ]
