# Generated by Django 4.2.9 on 2026-03-13 21:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_order_position_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='charges',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='buy_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='position',
            name='last_traded_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='realised_pnl',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='sell_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=12),
        ),
    ]
