# Generated by Django 6.0.4 on 2026-04-30 23:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_watchlist_options_alter_watchlist_user_and_more'),
        ('stockmanagement', '0006_alter_stock_ask_price_alter_stock_bid_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_margin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='leverage',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MarginPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=5)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('liquidated', 'Liquidated')], default='open', max_length=10)),
                ('leverage', models.PositiveSmallIntegerField(default=10)),
                ('margin_used', models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=20)),
                ('position_size', models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=20)),
                ('liquidation_price', models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=20)),
                ('realised_pnl', models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Margin Position',
                'verbose_name_plural': 'Margin Positions',
                'ordering': ['-opened_at'],
            },
        ),
    ]
