# Generated by Django 6.0.4 on 2026-05-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_margin_position_and_order_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginposition',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marginposition',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=20, null=True),
        ),
    ]
