# Generated by Django 5.2.11 on 2026-05-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_add_sltp_to_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marginposition',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='marginposition',
            name='take_profit',
        ),
        migrations.RemoveField(
            model_name='position',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='position',
            name='take_profit',
        ),
    ]
