# Generated by Django 4.2.9 on 2025-11-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='promo_type',
            field=models.CharField(choices=[('amount', 'Amount'), ('percentage', 'Percentage')], default='amount', help_text='Select whether this promo gives a fixed amount or a percentage discount.', max_length=20),
        ),
        migrations.AddField(
            model_name='promocode',
            name='reward_percentage',
            field=models.FloatField(blank=True, help_text='Enter the percentage value (used when promo type = percentage).', null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='reward_amount',
            field=models.FloatField(blank=True, help_text='Enter the bonus amount (used when promo type = amount).', null=True),
        ),
    ]
