# Generated by Django 4.2.9 on 2025-11-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(help_text='The promo code users will enter. Example: WELCOME100', max_length=50, unique=True)),
                ('reward_amount', models.FloatField(help_text='Bonus amount based on promo code.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
            },
        ),
        migrations.RemoveField(
            model_name='referralrelationship',
            name='referred',
        ),
        migrations.RemoveField(
            model_name='referralrelationship',
            name='referrer',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='ReferralRelationship',
        ),
    ]
