# Generated by Django 4.2.9 on 2025-11-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_promocode_remove_referralrelationship_referred_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
