# Generated by Django 4.2.9 on 2025-11-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_account_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ifsc_code',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='upi_id',
            field=models.CharField(default='', max_length=150),
        ),
    ]
